config/routes.rb
Rails.application.routes.draw do
  resources :numbers, only: [:index]

  root to: redirect('/numbers')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
  def index
  end

  helper_method :resources
  def resources
    @resources ||= Paginators::NumbersPaginator.new(per_page: params[:per_page], page: params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OneMillionPagination</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/numbers/index.html.erb
<h1>Numbers</h1>


<div class="row">
  <div class="col-xs-12 col-md-8">
    <ul class="pagination">
      <li><%= link_to 'Previous Page', numbers_path(page: resources.previous_page) unless resources.first_page? %></li>
      <li><%= link_to "Current Page: #{resources.page}", numbers_path(page: resources.page) %></li>
      <li><%= link_to 'Next Page', numbers_path(page: resources.next_page) unless resources.last_page? %></li>
    </ul>

    <p>Showing numbers <%= resources.first %> to <%= resources.last %>.</p>

    <ul>
      <% resources.each do |number| %>
        <li><%= number.to_words %></li>
      <% end %>
    </ul>

  </div>
  <div class="col-xs-12 col-md-4">
    <%= form_for resources, url: numbers_path, as: :number, method: :get, enforce_utf8: false do |f| %>
      <div class="form-group">
        <%= f.label :page %>
        <%= f.number_field :page, name: :page, min: 1, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :per_page %>
        <%= f.number_field :per_page, name: :per_page, min: 1, class: 'form-control' %>
      </div>

      <%= f.submit 'Update', class: 'btn btn-default', name: '' %>
    <% end %>
  </div>
</div>